/**
 * The build's single read of the ingested snapshot.
 *
 * `src/data/radar.json` is generated by `npm run ingest` and git-ignored, so a
 * fresh clone does not have it. Every page imports THIS module rather than the
 * JSON directly, for two reasons:
 *
 *   1. One place casts the parsed JSON to `RadarSnapshot`, so the rest of the
 *      site is typed rather than poking at `any`.
 *   2. One place fails loudly with an actionable message when the file is
 *      missing. A raw `import ... from '@/data/radar.json'` fails as
 *      "Cannot find module", which reads like a broken import rather than
 *      what it is: the build step has not been run.
 *
 * `npm run build` runs `ingest` first, and CI runs it before `typecheck` for
 * exactly this reason.
 */

import type { Digest, RadarSnapshot, RadarItem } from '@/types.ts';
import type { Snapshot as StudiesSnapshot, TaxonomyMaps } from '@/studies/types.ts';
import snapshotJson from '@/data/radar.json';
import studiesJson from '@/data/studies.json';
import studiesTaxonomiesJson from '@/data/studies-taxonomies.json';

export const snapshot = snapshotJson as unknown as RadarSnapshot;

export const research = snapshot.research;
export const campus = snapshot.campus;
export const digests: Digest[] = snapshot.digests ?? [];
export const studies = studiesJson as unknown as StudiesSnapshot;
export const studyTaxonomies = studiesTaxonomiesJson as unknown as TaxonomyMaps;

/** Every item across both ranked verticals, for detail-page routing. */
export const allItems: RadarItem[] = [...research.items, ...campus.items];

export const fetchedAt = snapshot.fetchedAt;

/**
 * A stable "now" for the whole build.
 *
 * Pages render relative times ("in 3 days"), and using the wall clock per page
 * would make two pages in the same build disagree. The ingest timestamp is the
 * honest reference point: it is when the data was actually true.
 */
export const now = snapshot.fetchedAt;
